const Products = [

    {
        id: 0,
        name: 'Taco',
        img: 'taco-bell.png',
        brand: 'pizzahub-logo.png',
        category: 'plats',
        delivery: true,
        discount: 25,
        wishlist: false,
        price: 800,
        old_price: 1000
    },
    {
        id: 1,
        name: 'Spaguetti Gras',
        img: 'noodles.png',
        brand: 'donut-hut-logo.png',
        category: 'plats',
        delivery: true,
        discount: 15,
        wishlist: false,
        price: 650,
        old_price: 450
    },
    {
        id: 2,
        name: 'Filet Porc',
        img: 'kuakata.png',
        brand: 'donuts-hut-logo.png',
        category: 'plats',
        delivery: true,
        discount: 5,
        wishlist: false,
        price: 750,
        old_price: 500
    },
    {
        id: 3,
        name: 'Steak Boeuf',
        img: 'steak.png',
        brand: 'donuts-hut-logo.png',
        category: 'plats',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 1000,
        old_price: 850
    },
    {
        id: 4,
        name: 'Pâtisserie',
        img: 'donuthut.png',
        brand: 'food-world-logo.png',
        category: 'desserts',
        delivery: true,
        discount: 25,
        wishlist: false,
        price: 800,
        old_price: 550
    },
    {
        id: 5,
        name: 'Barajii Eau Sachet',
        img: 'barajii_eau.png',
        brand: 'pizzahub-logo.png',
        category: 'boissons',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 100,
        old_price: 0
    },
    {
        id: 6,
        name: 'Fanta Canette',
        img: 'fanta.png',
        brand: 'taco-bell-logo.png',
        category: 'boissons',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 400,
        old_price: 500
    },
    {
        id: 7,
        name: 'Sandwich',
        img: 'sub-sandwich.png',
        brand: 'taco-bell-logo.png',
        category: 'plats',
        delivery: true,
        discount: 15,
        wishlist: false,
        price: 650,
        old_price: 450
    },
    {
        id: 8,
        name: 'Soupe Tai',
        img: 'thai-soup.png',
        brand: 'food-world-logo.png',
        category: 'plats',
        delivery: true,
        discount: 5,
        wishlist: false,
        price: 750,
        old_price: 500
    },
    {
        id: 9,
        name: 'Pizza',
        img: 'search-pizza.png',
        brand: 'pizzahub-logo.png',
        category: 'plats',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 1000,
        old_price: 1500
    },
    {
        id: 10,
        name: 'Beaufort Bouteille',
        img: 'beaufort.png',
        brand: 'red-square-logo.png',
        category: 'boissons',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 500,
        old_price: 0
    },
    {
        id: 11,
        name: 'Salade de fruits',
        img: 'discount-item-1.png',
        brand: 'food-world-logo.png',
        category: 'plats',
        delivery: true,
        discount: 25,
        wishlist: false,
        price: 800,
        old_price: 950
    },
    {
        id: 12,
        name: 'Patte Epicée',
        img: 'discount-item-2.png',
        brand: 'taco-bell-logo.png',
        category: 'plats',
        delivery: true,
        discount: 15,
        wishlist: true,
        price: 650,
        old_price: 450
    },
    {
        id: 13,
        name: 'Soupe Poulet',
        img: 'discount-item-3.png',
        brand: 'food-world-logo.png',
        category: 'plats',
        delivery: true,
        discount: 5,
        wishlist: false,
        price: 750,
        old_price: 500
    },
    {
        id: 14,
        name: 'Salade',
        img: 'discount-item-4.png',
        brand: 'taco-bell-logo.png',
        category: 'plats',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 1000,
        old_price: 850
    },
    {
        id: 15,
        name: 'Chill Bouteille',
        img: 'petite-chill.png',
        brand: 'taco-bell-logo.png',
        category: 'boissons',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 500,
        old_price: 0
    },
    {
        id: 16,
        name: 'Steak Boeuf',
        img: 'steak.png',
        brand: 'donuts-hut-logo.png',
        category: 'plats',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 1000,
        old_price: 850
    },
    {
        id: 17,
        name: 'Yaourt Fraise',
        img: 'yaourt-fraise.png',
        brand: 'food-world-logo.png',
        category: 'desserts',
        delivery: true,
        discount: 12,
        wishlist: true,
        price: 1000,
        old_price: 850
    },
    {
        id: 18,
        name: 'Eau Laafi',
        img: 'eau-lafi.png',
        brand: 'donuts-hut-logo.png',
        category: 'boissons',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 1000,
        old_price: 850
    },
    {
        id: 19,
        name: 'Brochette Mouton',
        img: 'brochette.png',
        brand: 'food-world-logo.png',
        category: 'plats',
        delivery: true,
        discount: 12,
        wishlist: false,
        price: 200,
        old_price: 850
    },
    {
        id: 20,
        name: 'Jus Mangue',
        img: 'mangue.png',
        brand: 'food-world-logo.png',
        category: 'boissons',
        delivery: true,
        discount: 12,
        wishlist: true,
        price: 1000,
        old_price: 850
    },

];

export default Products;